version: "3.9"

services:

  postgres:
    image: postgres:15
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  cache_bootstrap:
    build:
      context: .
      dockerfile: sync_worker/Dockerfile
    command: ["python", "-m", "sync_worker.bootstrap_app"]
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: "no"

  sync_worker:
    build:
      context: .
      dockerfile: sync_worker/Dockerfile
    env_file:
      - .env
    depends_on:
      counters_api:
        condition: service_started
    restart: always

  counters_api:
    build:
      context: .
      dockerfile: counters_api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      cache_bootstrap:
        condition: service_completed_successfully
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - counters_api
    restart: always

volumes:
  postgres_data:
  redis_data: